[versions]
componentsResources = "1.10.1"
foundationVersion = "1.10.1"
graphicsCore = "1.0.4"
htmlCore = "1.10.1"
kotlin = "2.3.10"
compose = "1.10.1"
agp = "9.0.1"
androidx-activityCompose = "1.12.4"
kotlinxBrowser = "0.5.0"
kotlinxCoroutinesSwing = "1.10.2"
material3 = "1.10.0-alpha05"
maven-publish = "0.36.0"
runtime = "1.10.1"
startupRuntime = "1.2.0"
uiToolingPreview = "1.10.1"
coreKtx = "1.17.0"
material3Version = "1.4.0"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-graphics-core = { module = "androidx.graphics:graphics-core", version.ref = "graphicsCore" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
html-core = { module = "org.jetbrains.compose.html:html-core", version.ref = "htmlCore" }
jetbrains-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundationVersion" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesSwing" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutinesSwing" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "uiToolingPreview" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiToolingPreview" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Version" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
android-library = { id = "com.android.library", version.ref = "agp" }
